### ISSUE TITLE
Add a way to update spec files without needing to reindex all gems

### ISSUE THREAD

**Issue by hemmrich** [PierreRambaud/gemirro#10]
It seems that the [Gem::Indexer class](http://ruby-doc.org/stdlib-2.2.2/libdoc/rubygems/rdoc/Gem/Indexer.html) provides functions to update specs/indices so that older gems that are already indexed are skipped over. This would be very useful, since indexing 580k gems takes upwards of 4 hours. Can this functionality be added to gemirro, possibly via a ```gemirro index --update``` command? I could work on the implementation if you'd be okay with adding this functionality.

**Comment by PierreRambaud** [comment]
Yes sur, I will have a look as soon as possible :)

**Comment by PierreRambaud** [comment]
My bad don't see the last line, if you want to work on it, sure you can :+1:

**Comment by PierreRambaud** [comment]
Same on https://github.com/PierreRambaud/gemirro/blob/master/lib/gemirro/server.rb#L150 it index all the gems instead of only the fetched gem.

**Comment by PierreRambaud** [comment]
I added a `--update` for `gemirro index` command.
it should be fix the problem.
