### ISSUE TITLE
How does Gemirro deal with platforms?

### ISSUE THREAD

**Issue by dgoradia** [PierreRambaud/gemirro#14]
How do you deal with gems for different platforms?

So if Gemirro is on a Linux server, it downloads the gems for its own platform. 

What if the connecting machine (the one that runs `gem install xxx` is a Mac or a Windows? It will request a mingw32, for example, but that isn't on the Gemirro server.

**Comment by PierreRambaud** [comment]
Hi and sorry for the delay,
Gemirro just get the request from rubygems (gem command, or bundle command) and respond exactly as rubygems.org.
I admit to not having tested under MAC or Windows (because I don't have theses systems :/) but some gems downloaded on production (at work) request mingw32 under unix system (only for gemspec) and they are downloaded.
Regards

**Comment by dgoradia-atlas** [comment]
Thanks for your response. On Mac it was requesting mingw32 which wasn't on the gemirro server but also wasn't being downloaded to the gemirro mirror from rubygems. I'm not sure why but I will have to debug some more when I get some time. In the meantime, I've gone back to using `gem server`.

**Comment by PierreRambaud** [comment]
Sorry for the delay, I'm currently in vacation. I will try to have a look as soon as possible.

**Comment by PierreRambaud** [comment]
Hi,
After viewing some websites, I can't find any OSX boxes :/ Do you have the capability to create a vagrant box from your MAC?
Regards

**Comment by dgoradia-atlas** [comment]
I can probably probably try to create a clean install but I'm not sure whether it would work on a non-osx host. 

Here are two I found

https://atlas.hashicorp.com/jhcook/boxes/osx-yosemite-10.10

https://github.com/AndrewDryga/vagrant-box-osx?files=1

**Comment by PierreRambaud** [comment]
Thanks a lot, I will try when boxes will be downloaded (Only 42hours of download --')

**Comment by PierreRambaud** [comment]
I tried to reproduce in OSX box, but it seems to work :/ Which gem did you try to install?

Regards

**Comment by dgoradia-atlas** [comment]
I tried to install chef 12.3.0 on an OS X 10.9 while the gemirro server was on a centos linux box.

**Comment by PierreRambaud** [comment]
I'm really sorry, I'm currently very busy and don't have the time to have a look for now. I will be back as soon as possible.

**Comment by PierreRambaud** [comment]
Sorry I can't reproduce this bug. If you have any information about how to reproduce it quickly, don't hesitate.
