### ISSUE TITLE
Doesn't support ruby 2+?

### ISSUE THREAD

**Issue by treenewbee** [PierreRambaud/gemirro#16]
Version 4 of Slop is aimed at Ruby 2.0 or later. Please use Version 3 for Ruby 1.9 support.

Also rspec fails a lot.  

cli_spec needs
require 'gemirro/version'

server_spec needs
require 'sinatra/base'
require 'thin'

**Comment by PierreRambaud** [comment]
Hi,

Version 3 of slop works with Ruby > 2.
Can you show me which errors do you see, I work with 2.1.5 and execute all tests on 1.9.3, 2.0.0 and 2.1.0 (https://travis-ci.org/PierreRambaud/gemirro)

Regards

**Comment by treenewbee** [comment]
I got the same error below, thought it was slop, but maybe not. 
https://github.com/PierreRambaud/gemirro/issues/15

Using 2.2.2:

Failures:

  1) CLI should return options
     Failure/Error: expect { version.call }.to output(/gemirro v.* on ruby/).to_stdout
     NameError:
       uninitialized constant Gemirro::CLI::VERSION
     # ./lib/gemirro/cli.rb:60:in `version_information'
     # ./lib/gemirro/cli.rb:49:in `block (2 levels) in default_options'
     # ./spec/gemirro/cli_spec.rb:28:in `block (3 levels) in <module:CLI>'
     # ./spec/gemirro/cli_spec.rb:28:in `block (2 levels) in <module:CLI>'

  2) CLI should retrieve version information
     Failure/Error: expect(CLI.version_information).to eq(
     NameError:
       uninitialized constant Gemirro::CLI::VERSION
     # ./lib/gemirro/cli.rb:60:in `version_information'
     # ./spec/gemirro/cli_spec.rb:32:in `block (2 levels) in <module:CLI>'

  3) Gemirro::Server HTML render should display index page
     Failure/Error: require 'gemirro/server'
     LoadError:
       cannot load such file -- sinatra/base
     # ./lib/gemirro/server.rb:2:in `<top (required)>'
     # ./spec/gemirro/server_spec.rb:16:in `app'
     # ./spec/gemirro/server_spec.rb:45:in `block (3 levels) in <module:Gemirro>'

  4) Gemirro::Server HTML render should return 404
     Failure/Error: require 'gemirro/server'
     LoadError:
       cannot load such file -- sinatra/base
     # ./lib/gemirro/server.rb:2:in `<top (required)>'
     # ./spec/gemirro/server_spec.rb:16:in `app'
     # ./spec/gemirro/server_spec.rb:50:in `block (3 levels) in <module:Gemirro>'

  5) Gemirro::Server HTML render should return 404 when gem does not exist
     Failure/Error: require 'gemirro/server'
     LoadError:
       cannot load such file -- sinatra/base
     # ./lib/gemirro/server.rb:2:in `<top (required)>'
     # ./spec/gemirro/server_spec.rb:16:in `app'
     # ./spec/gemirro/server_spec.rb:56:in `block (3 levels) in <module:Gemirro>'

  6) Gemirro::Server HTML render should display gem specifications
     Failure/Error: require 'gemirro/server'
     LoadError:
       cannot load such file -- sinatra/base
     # ./lib/gemirro/server.rb:2:in `<top (required)>'
     # ./spec/gemirro/server_spec.rb:16:in `app'
     # ./spec/gemirro/server_spec.rb:108:in `block (3 levels) in <module:Gemirro>'

  7) Gemirro::Server Download should download existing file
     Failure/Error: require 'gemirro/server'
     LoadError:
       cannot load such file -- sinatra/base
     # ./lib/gemirro/server.rb:2:in `<top (required)>'
     # ./spec/gemirro/server_spec.rb:16:in `app'
     # ./spec/gemirro/server_spec.rb:116:in `block (3 levels) in <module:Gemirro>'

  8) Gemirro::Server Download should try to download gems.
     Failure/Error: require 'gemirro/server'
     LoadError:
       cannot load such file -- sinatra/base
     # ./lib/gemirro/server.rb:2:in `<top (required)>'
     # ./spec/gemirro/server_spec.rb:16:in `app'
     # ./spec/gemirro/server_spec.rb:150:in `block (3 levels) in <module:Gemirro>'

  9) Gemirro::Server Download should catch exceptions
     Failure/Error: require 'gemirro/server'
     LoadError:
       cannot load such file -- sinatra/base
     # ./lib/gemirro/server.rb:2:in `<top (required)>'
     # ./spec/gemirro/server_spec.rb:16:in `app'
     # ./spec/gemirro/server_spec.rb:191:in `block (3 levels) in <module:Gemirro>'

  10) Gemirro::Server dependencies should retrieve nothing
      Failure/Error: require 'gemirro/server'
      LoadError:
        cannot load such file -- sinatra/base
      # ./lib/gemirro/server.rb:2:in `<top (required)>'
      # ./spec/gemirro/server_spec.rb:16:in `app'
      # ./spec/gemirro/server_spec.rb:198:in `block (3 levels) in <module:Gemirro>'

  11) Gemirro::Server dependencies should retrieve empty json
      Failure/Error: require 'gemirro/server'
      LoadError:
        cannot load such file -- sinatra/base
      # ./lib/gemirro/server.rb:2:in `<top (required)>'
      # ./spec/gemirro/server_spec.rb:16:in `app'
      # ./spec/gemirro/server_spec.rb:206:in `block (3 levels) in <module:Gemirro>'

  12) Gemirro::Server dependencies should retrieve empty json when gem was not found
      Failure/Error: require 'gemirro/server'
      LoadError:
        cannot load such file -- sinatra/base
      # ./lib/gemirro/server.rb:2:in `<top (required)>'
      # ./spec/gemirro/server_spec.rb:16:in `app'
      # ./spec/gemirro/server_spec.rb:214:in `block (3 levels) in <module:Gemirro>'

  13) Gemirro::Server dependencies should retrieve json when gem was found
      Failure/Error: allow_any_instance_of(Gemirro::Server).to receive(:gems_collection)
      NameError:
        uninitialized constant Gemirro::Server
      # ./spec/gemirro/server_spec.rb:258:in `block (3 levels) in <module:Gemirro>'

Finished in 0.51881 seconds (files took 1.09 seconds to load)
75 examples, 13 failures

Failed examples:

rspec ./spec/gemirro/cli_spec.rb:14 # CLI should return options
rspec ./spec/gemirro/cli_spec.rb:31 # CLI should retrieve version information
rspec ./spec/gemirro/server_spec.rb:40 # Gemirro::Server HTML render should display index page
rspec ./spec/gemirro/server_spec.rb:49 # Gemirro::Server HTML render should return 404
rspec ./spec/gemirro/server_spec.rb:55 # Gemirro::Server HTML render should return 404 when gem does not exist
rspec ./spec/gemirro/server_spec.rb:61 # Gemirro::Server HTML render should display gem specifications
rspec ./spec/gemirro/server_spec.rb:115 # Gemirro::Server Download should download existing file
rspec ./spec/gemirro/server_spec.rb:121 # Gemirro::Server Download should try to download gems.
rspec ./spec/gemirro/server_spec.rb:162 # Gemirro::Server Download should catch exceptions
rspec ./spec/gemirro/server_spec.rb:197 # Gemirro::Server dependencies should retrieve nothing
rspec ./spec/gemirro/server_spec.rb:205 # Gemirro::Server dependencies should retrieve empty json
rspec ./spec/gemirro/server_spec.rb:213 # Gemirro::Server dependencies should retrieve empty json when gem was not found
rspec ./spec/gemirro/server_spec.rb:221 # Gemirro::Server dependencies should retrieve json when gem was found

**Comment by PierreRambaud** [comment]
Did you do a `bundle install` and run tests with `bundle exec`?

**Comment by treenewbee** [comment]
Did bundle install, but didn't bundle exec rspec. Adding bundle exec before rspec passes all the tests for me.

**Comment by PierreRambaud** [comment]
Nice, thanks for your feedback :)
