### ISSUE TITLE
Over 2GiB Memory Consumption

### ISSUE THREAD

**Issue by martinvahi** [PierreRambaud/gemirro#17]
There must be something wrong. That kind of memory consumption is just unpractical.

**Comment by PierreRambaud** [comment]
Hi,
Thanks for your feedback, I'm currently busy, I will try to have a look as soon as possible. If you have any idea about what's happened don't hesitate to tell me :/

Regards

**Comment by martinvahi** [comment]
One test that can be tried out is 

    gem install rails

through the gemirro. Works fine if done directly from [https://rubygems.org](https://rubygems.org)

**Comment by PierreRambaud** [comment]
I'm making some tests and gemirro use at least 4GiB of memory when requesting gems. I'm trying to profile sinatra, but it looks like to be harder than expected :/

**Comment by PierreRambaud** [comment]
I juste whant to say, Why ruby don't have a garbage collector to manage -_-'
