### ISSUE TITLE
Looking for .rz files that does not exist

### ISSUE THREAD

**Issue by gjngeldenhuis** [PierreRambaud/gemirro#19]
My gemirro service is looking for files in:
GET /quick/Marshal.4.8/colored-1.2.gemspec.rz HTTP/1.1" 404 1204 0.0011

The /quick/Marshal.4.8/ directory exists but is empty. My whole tree of mirrored gems does not have a single .rz file on .gem files. 

So I am perplexed as to why it is looking for a .rz file and where it expects to find this .rz file? The result at the moment is that I get the following error message when trying to use my gem service:
gem install colored
ERROR:  Could not find a valid gem 'colored' (>= 0) in any repository

**Comment by PierreRambaud** [comment]
Hi and thanks for the feedback, it should be fixed with the latest commit.

Regards

**Comment by gjngeldenhuis** [comment]
Great! Do you have an expectation of when 0.12 would be on rubygems?

**Comment by PierreRambaud** [comment]
It's released on rubygems ;)
