### ISSUE TITLE
Auto dependency pull down of gems

### ISSUE THREAD

**Issue by gjngeldenhuis** [PierreRambaud/gemirro#21]
Currently when downloading gems, gemirro will only download exactly what I have specified. It would be nice to have a flag or configuration item that I can use to specify to also download related dependencies. As the amount of gems gets more that I have to mirror the list of gems is getting really long. My use case is using gemirro to replace rubygems in a non-internet environment.

**Comment by PierreRambaud** [comment]
Hi, I'm sorry, I was really busy lately.
If you want to create a non-internet environment, I suggest you to use "gem mirror" command  (https://github.com/rubygems/rubygems-mirror).

Regards
