### ISSUE TITLE
How to only keep the latest version of a package

### ISSUE THREAD

**Issue by cykerway** [PierreRambaud/gemirro#22]
Is there a way to specify the items in `define_source` so that only the latest version of a package is kept?

For example, if I write

    gem 'bigdecimal' 

then gemirro will fetch multiple versions of the same gem. However, I'm only interested in the latest version synchronized from upstream source.

**Comment by cykerway** [comment]
By the way, I saw it's possible to add a requirement such `>= 1.0.0` for a gem. But I guess this type of version specification is not quite general since one has to look up the latest version number one gem after another. It'd be great if the requirement can have a form like *latest* or *newest*.

**Comment by PierreRambaud** [comment]
Hi, I'm sorry, I was really busy lately.
In fact, version parameter are use for ::Gem::Indexer and many other RubyGems classes, the only way to retrieve only the latest version is to write exactly what you did in your first message.
I will try to investigate on this issue as soon as possible.

Regards

**Comment by cykerway** [comment]
Thank you for ack. Do you mean

    gem 'bigdecimal'

should fetch only the latest version but currently doesn't?

**Comment by PierreRambaud** [comment]
No, 

    gem 'bigdecimal'

must fetch all versions, but I imagine more something like this:

    gem 'bigdecimal', :latest
    # or
    gem 'bigdecimal', :newest

**Comment by PierreRambaud** [comment]
I tried with many gems and seems to work now with the latest commit ;)

**Comment by PierreRambaud** [comment]
I will release a new version in few hours

**Comment by PierreRambaud** [comment]
I close this issue, don't hesitate to create a bug if something wrong occured.
Regards
