### ISSUE TITLE
Update and index dependance on service running

### ISSUE THREAD

**Issue by gjngeldenhuis** [PierreRambaud/gemirro#23]
I just want to clarify whether the following commands:
gemirro update
gemirro index
gemirro index --update

can be run when gemirro server is running or is the intention to stop the service, run them and then restart the service?

**Comment by PierreRambaud** [comment]
Hi, I'm sorry, I was really busy lately.
All command can be run when the server is running, But if a problem occurred, don't hesitate to create a bug :)
Regards

**Comment by gjngeldenhuis** [comment]
So consider this a bug report then. Since running update and index separately while the service is running does not appear to make the newer gems available. I will test it again to confirm.

**Comment by PierreRambaud** [comment]
FYI, it works for me, no need to restart the server.
