### ISSUE TITLE
Gemirro init does not support config file

### ISSUE THREAD

**Issue by gjngeldenhuis** [PierreRambaud/gemirro#24]
I would like to be able to use a config file when initializing the server. The intend is that it should make use of the config file and the locations that I have set in there, rather than overwrite the config file.

**Comment by PierreRambaud** [comment]
Hi, I'm sorry, I was really busy lately.
Can you tell me more about the config file?
Look for something like this:

`̀̀``
destination: /tmp/repo
gems:
  - rake: 
    version: 10.0.0
  - usblamp
  - chef  
`̀̀``

**Comment by gjngeldenhuis** [comment]
What I mean is that if I run gemirro init in /var/spool/gemirro/test2 directory it will create a config.rb file. What I would like is that if there already is a config.rb file that it does not get overwriten and that this line for example gets honoured:
destination File.expand_path('/var/spool/gemirro/test2/public', __FILE__)

**Comment by PierreRambaud** [comment]
Should be fix with the latest commit, it check if file exists before copy them. More I add an option to allow overwrite "--force".

Regards
