### ISSUE TITLE
gemirro server --status gives error

### ISSUE THREAD

**Issue by gjngeldenhuis** [PierreRambaud/gemirro#25]
If the gemirro service is not running and your run the command: gemirro server --status you get an error. The expected result is just a simple line saying not running with an exit code of 1. Instead at the moment I am getting the following:
Error: PID File not found /var/spool/gemirro/test2/gemirro.pid
/var/lib/gems/1.9.1/gems/gemirro-0.12.0/lib/gemirro/cli/server.rb:113:in `getpgid': no implicit conversion from nil to integer (TypeError)
	from /var/lib/gems/1.9.1/gems/gemirro-0.12.0/lib/gemirro/cli/server.rb:113:in `running?'
	from /var/lib/gems/1.9.1/gems/gemirro-0.12.0/lib/gemirro/cli/server.rb:105:in `status'
	from /var/lib/gems/1.9.1/gems/gemirro-0.12.0/lib/gemirro/cli/server.rb:20:in `block (2 levels) in <top (required)>'
	from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	from /var/lib/gems/1.9.1/gems/gemirro-0.12.0/bin/gemirro:7:in `<top (required)>'
	from /usr/local/bin/gemirro:23:in `load'
	from /usr/local/bin/gemirro:23:in `<main>'

**Comment by PierreRambaud** [comment]
Thanks a lot for your feedback ;)

**Comment by gjngeldenhuis** [comment]
The error message currently is:
gemirro server --status --config /etc/gemirro/config.rb
Error: PID File not found /var/spool/gemirro/test2/gemirro.pid
gemirro is running

I suspect it is a typo but it should have a not added.
gemirro is not running.

**Comment by gjngeldenhuis** [comment]
Also MUCH more importantly, the exit code should be 1 if gemirro is not running, as it helps to determine very easily in other scripts what the status is.

**Comment by PierreRambaud** [comment]
Released, I will improve readme today.
