### ISSUE TITLE
If config file is not named config.rb then gemirro fails

### ISSUE THREAD

**Issue by gjngeldenhuis** [PierreRambaud/gemirro#26]
If I try to run gemirro as follows:
/usr/local/bin/gemirro server --start --config /etc/gemirro/gemirro.rb

I get this error message:
The configuration file /etc/gemirro/gemirro.rb/config.rb does not exist

It should really not care what it is called as long as it can find the file.

**Comment by PierreRambaud** [comment]
Thanks again, it's fixed :)

**Comment by gjngeldenhuis** [comment]
Awesome! When were you planning on pushing the new release to rubygems?

**Comment by PierreRambaud** [comment]
Maybe tomorrow, need try to work on one thing before release :)

**Comment by gjngeldenhuis** [comment]
Great, thanks! FYI, I am making a puppet module to manage gemirro and all of the configuration, hence all the bug reports.
