### ISSUE TITLE
Additional info via command line

### ISSUE THREAD

**Issue by gjngeldenhuis** [PierreRambaud/gemirro#28]
It would be useful to get a list of gems and their version via the command line from the server while it is running. It could serve as a debugging/verification tool to know and ensure that the gems are actually available.

**Comment by PierreRambaud** [comment]
New release available.

**Comment by gjngeldenhuis** [comment]
I have downloaded the new release but I can't see any relevant command related to this ticket. Is there a new command available to query gems that gemirro has downloaded?

**Comment by PierreRambaud** [comment]
Sorry my bad, i forgot to update README file.
You can use `gemirro list`, if you need more options for this command, don't hesitate to tell me ;)

Regards

**Comment by gjngeldenhuis** [comment]
No worries, I have been meaning to send a PR with some documentation updates at some stage.

gemirro list --config /etc/gemirro/config.rb

Does not return any results back for me. I ran an update, index and restarted the server but to no avail. I am expecting to see at least all the versions of rack. I am caching the following files:
define_source 'rubygems', 'http://rubygems.org' do
    gem 'rack', '>= 1.1.0'
end

**Comment by PierreRambaud** [comment]
Seems there is a bug due to latest version of Rubygems, I will fix this today.

**Comment by gjngeldenhuis** [comment]
Thanks! Looking forward to the next release.
