### ISSUE TITLE
gemirro 0.13.0 on rubygems.org is missing files

### ISSUE THREAD

**Issue by cykerway** [PierreRambaud/gemirro#29]
After

    gem install gemirro

I tried to run

    gem 'rack', :latest

and found this

>   ...cannot load such file -- gemirro/utils (LoadError)

So I did a diff between HEAD of this repo and `gem install gemirro`. It seems that the latter is missing some files:

>   Only in ./lib/gemirro/cli: list.rb
>   Only in ./lib/gemirro: utils.rb
>   Only in ./spec/gemirro: cache_spec.rb

Not sure it's relevant here because the HEAD of this repo does work correctly. It looks like a different commit of gemirro is submitted to rubygems?

**Comment by PierreRambaud** [comment]
Hi, really sorry I forgot to update Manifest file :/
I push a new version just now.
Thanks for your feedback!
