### ISSUE TITLE
gemirro list --config /etc/gemirro/config.rb gives back no listing

### ISSUE THREAD

**Issue by gjngeldenhuis** [PierreRambaud/gemirro#30]
When running gemirro list --config /etc/gemirro/config.rb I get back no listing at all, even though there should be 10 listed versions of one gem. I can install the gems using the server, but they don't turn up on the listing. I am using 0.13.3 of gemirro.

**Comment by PierreRambaud** [comment]
Hi,
Can you tell me wich version of rubygems are you using with this command:
`gem --version`

Regards

**Comment by gjngeldenhuis** [comment]
1.8.23
