### ISSUE TITLE
Clarification on comments in default config file required

### ISSUE THREAD

**Issue by ggeldenhuis** [PierreRambaud/gemirro#31]
Quoted from a default config file: 
All gem in the block will be downloaded with the update command.
Other gems will be downloaded with the server.
  define_source 'rubygems', 'http://rubygems.org' do

What does "other gems" refer to? Is there a different code block that can/should get used by server? There is no example or reference in the default config file so it is unclear what this refers to.

**Comment by PierreRambaud** [comment]
In fact, other gems are from `gem install` command, for example, you don't specify any gems in `define_source` and use `gem install volay`, this gem and its dependencies will be downloaded from the server (`server --start`). But it's clearly faster to define dependencies directly in `define_source` block.

**Comment by gjngeldenhuis** [comment]
Ah ok, so if you don't specify gems, gemirro will still attempt to download them, in affect acting as a proxy server. I tested this and got the following error:
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://knersus.net:2000/gems/mixlib-cli-1.5.0.gem)

When looking through the directory structure I see the following:
    ├── gems
    │   ├── sqlite3-1.3.10.gem
    │   ├── sqlite3-1.3.11.gem
    │   ├── sqlite3-1.3.3.beta.1.gem
    │   ├── sqlite3-1.3.3.gem
    │   ├── sqlite3-1.3.4.gem
    │   ├── sqlite3-1.3.5.gem
    │   ├── sqlite3-1.3.6.gem
    │   ├── sqlite3-1.3.7.gem
    │   ├── sqlite3-1.3.8.gem
    │   └── sqlite3-1.3.9.gem
    ├── latest_specs.4.8
    ├── latest_specs.4.8.gz
    ├── latest_specs.4.8.gz.orig
    ├── prerelease_specs.4.8
    ├── prerelease_specs.4.8.gz
    ├── prerelease_specs.4.8.gz.orig
    ├── quick
    │   └── Marshal.4.8
    │       ├── atk-2.2.5.gemspec.rz
    │       ├── cairo-1.14.0.gemspec.rz
    │       ├── cairo-1.14.1.gemspec.rz
    │       ├── cairo-1.14.2.gemspec.rz
    │       ├── cairo-1.14.3.gemspec.rz
    │       ├── cairo-gobject-2.2.5.gemspec.rz
    │       ├── gdk3-2.2.5.gemspec.rz
    │       ├── gdk_pixbuf2-2.2.5.gemspec.rz
    │       ├── gio2-2.2.5.gemspec.rz
    │       ├── glib2-2.2.5.gemspec.rz
    │       ├── gobject-introspection-2.2.5.gemspec.rz
    │       ├── gtk3-2.2.0.gemspec.rz
    │       ├── gtk3-2.2.1.gemspec.rz
    │       ├── gtk3-2.2.2.gemspec.rz
    │       ├── gtk3-2.2.3.gemspec.rz
    │       ├── gtk3-2.2.4.gemspec.rz
    │       ├── gtk3-2.2.5.gemspec.rz
    │       ├── mixlib-cli-1.5.0.gemspec.rz
    │       ├── mixlib-shellout-2.0.0.gemspec.rz
    │       ├── mixlib-shellout-2.0.1.gemspec.rz
    │       ├── mixlib-shellout-2.1.0.gemspec.rz
    │       ├── mixlib-shellout-2.2.0.gemspec.rz
    │       ├── mixlib-shellout-2.2.1.gemspec.rz
    │       ├── mixlib-shellout-2.2.2.gemspec.rz
    │       ├── mixlib-shellout-2.2.3.gemspec.rz
    │       ├── mixlib-shellout-2.2.5.gemspec.rz
    │       ├── pango-2.2.5.gemspec.rz
    │       ├── pkg-config-1.1.5.gemspec.rz
    │       ├── pkg-config-1.1.6.gemspec.rz
    │       ├── sqlite3-1.3.11.gemspec.rz
    │       └── volay-0.6.0.gemspec.rz
    ├── specs.4.8
    ├── specs.4.8.gz
    └── specs.4.8.gz.orig

So it has downloaded and cache some files but the actual gem seems to be missing

**Comment by gjngeldenhuis** [comment]
The config file that I am using:
# -*- coding: utf-8 -*-
# This file is managed by the gemirro puppet module.
# Modifications to this file is likely to be overwritten,
# by the puppet agent. You have been warned.

Gemirro.configuration.configure do
  # Define sinatra environment
  environment :production

  # The directory to store indexing information as well as the Gem files in.
  destination File.expand_path('/var/spool/gemirro/test2/public', __FILE__)

  logger.level = Logger::INFO

  server.host '10.10.10.10'
  server.port '2000'

  server.access_log File.expand_path('/var/log/gemirro/access.log', __FILE__)
  server.error_log File.expand_path('/var/log/gemirro/error.log', __FILE__)

  # All gem in the block will be downloaded with the update command.
  # Other gems will be downloaded with the server.

  define_source 'rubygems', 'http://rubygems.org' do
    gem 'gemirro', '>= 1.0.0'
    gem 'sqlite3', '>= 1.0.0'
  end
end

**Comment by PierreRambaud** [comment]
In fact, it's normal, there're so many dependencies to download for some gems that the gem command raise a timeout error, that's why adding them in define_source is safier an faster.

**Comment by gjngeldenhuis** [comment]
Well... yeah but then if I run it a second time it should work or try again? Instead it fails.

**Comment by PierreRambaud** [comment]
Yeah it should try again

**Comment by gjngeldenhuis** [comment]
The fact that it does not try again, would you consider that a bug?

**Comment by PierreRambaud** [comment]
Issue's too old.
