### ISSUE TITLE
Getting bad response error with no way of recovering

### ISSUE THREAD

**Issue by ggeldenhuis** [PierreRambaud/gemirro#32]
I have the created the following setup:
* Gemirror server machine directly connected to the internet (fast connection)
* Client machine connected to the server machine but not the internet.
* I have added a gemsource to my client machine that points to my gemirro server and I have deleted all other gemsources

This is my config.rb file:
```
Gemirro.configuration.configure do
  # Define sinatra environment
  environment :production

  # The directory to store indexing information as well as the Gem files in.
  destination File.expand_path('/var/spool/gemirro/public', __FILE__)

  logger.level = Logger::INFO

  server.host '192.168.102.128'
  server.port '2000'

  server.access_log File.expand_path('/var/log/gemirro/access.log', __FILE__)
  server.error_log File.expand_path('/var/log/gemirro/error.log', __FILE__)

  # All gem in the block will be downloaded with the update command. ???
  # Other gems will be downloaded with the server. ??? What does this mean
  define_source 'rubygems', 'http://rubygems.org' do
  end
end
```

When I try to install razor-client for example on the client machine my expectation is that:
* gemirro will fetch all necessary gems on my behalf
* the gem will install.

Instead I get the following error message:
`ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://192.168.102.128:2000/gems/mime-types-1.25.1.gem)`

No amount of restarting the gemirro server seems to fix the issue.

**Comment by nareiber** [comment]
Did you get help with this? There are no gems set for your source. You must specify the gems to mirror[1].

https://github.com/PierreRambaud/gemirro/blob/master/lib/gemirro/source.rb#L22
