### ISSUE TITLE
Are you able to configure Gemirro to use a proxy

### ISSUE THREAD

**Issue by mdurden** [PierreRambaud/gemirro#36]
I have tried using Env Vars: http_proxy, HTTP_PROXY... Gemirro doesn't seem to pick up on them. Is there a way to configure it in the config.rb?

**Comment by PierreRambaud** [comment]
Hi, with which Ruby version are you running it?

**Comment by mdurden** [comment]
Running it with 2.3
Full disclosure: I am trying to run gemirro inside a docker container. Name:Tag => ruby:2.3

**Comment by mdurden** [comment]
Actually, after playing with it a bit more; it seems I was wrong... It does appear to be picking up on the proxy env vars. Just chalk this up to me being a moron. Thanks for the response.

**Comment by PierreRambaud** [comment]
No problem, Thanks for your feedback ;)
