### ISSUE TITLE
Fail on missing gems?

### ISSUE THREAD

**Issue by iiezhachenko** [PierreRambaud/gemirro#43]
When I'm downloading gem which has dependencies from Gemirro, it consumes whole memory and crashes. 

Is there a possibility to return something like "Not found", if gem is not in index, so it will be pulled from rubygems? This way Gemirro will store only private gems, and will stop trying to be a replacement for RubyGems.

**Comment by PierreRambaud** [comment]
Hi, can you try with latest version (on github) ?
You can add `fetch_gem false` in your config file

Regards

**Comment by iiezhachenko** [comment]
Sorry for the delay.
My config:
`# -*- coding: utf-8 -*-
Gemirro.configuration.configure do
  environment :production
  destination File.expand_path('../public', __FILE__)
  logger.level = Logger::INFO
  fetch_gem false
  server.access_log File.expand_path('../logs/access.log', __FILE__)
  server.error_log File.expand_path('../logs/error.log', __FILE__)
  define_source 'rubygems', 'http://rubygems.org' do
    gem 'rack', '>= 1.0.0'
    gem 'gli', '>= 2.0.0'
  end
end`

Gem output

`gem install -V samples_sender --source http://gemirro.mydomain.com
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.gemirro.mydomain.com
HEAD http://gemirro.mydomain.com/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=samples_sender
200 OK
GET http://gemirro.mydomain.com/api/v1/dependencies?gems=samples_sender
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.gemirro.mydomain.com
GET https://api.rubygems.org/api/v1/dependencies?gems=archive-zip,dropbox-sdk,gli,mailgun-ruby,methadone
200 OK
GET http://gemirro.mydomain.com/api/v1/dependencies?gems=archive-zip,dropbox-sdk,gli,mailgun-ruby,methadone
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=bundler,io-like,json,rest-client
200 OK
GET http://gemirro.mydomain.com/api/v1/dependencies?gems=bundler,io-like,json,rest-client
502 Bad Gateway
GET http://gemirro.mydomain.com/prerelease_specs.4.8.gz
502 Bad Gateway
GET http://gemirro.mydomain.com/specs.4.8.gz
200 OK
GET http://gemirro.mydomain.com/quick/Marshal.4.8/rest-client-2.0.0.gemspec.rz
502 Bad Gateway
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Bad Gateway 502 (http://gemirro.mydomain.com/quick/Marshal.4.8/rest-client-2.0.0.gemspec.rz)`

**Comment by iiezhachenko** [comment]
After that Gemirro consumed 8Gb of RAM and host stopped responding.

**Comment by PierreRambaud** [comment]
Hi,
Can you retry with latest commit?

My result : 
```
$ gem install -V simple_messenger --source http://localhost:2000
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.localhost
HEAD http://localhost:2000/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=simple_messenger
200 OK
GET http://localhost:2000/api/v1/dependencies?gems=simple_messenger
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=activerecord
200 OK
GET http://localhost:2000/api/v1/dependencies?gems=activerecord
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=activemodel,activerecord-deprecated_finders,activesupport,arel
200 OK
GET http://localhost:2000/api/v1/dependencies?gems=activemodel,activerecord-deprecated_finders,activesupport,arel
connection reset after 1 requests, retrying
GET http://localhost:2000/api/v1/dependencies?gems=activemodel,activerecord-deprecated_finders,activesupport,arel
connection reset after 1 requests, retrying
Getting SRV record failed: DNS result has no information for _rubygems._tcp.localhost
GET http://localhost:2000/prerelease_specs.4.8.gz
200 OK
GET http://localhost:2000/specs.4.8.gz
200 OK
GET http://localhost:2000/quick/Marshal.4.8/activesupport-4.0.13.gemspec.rz
404 Not Found
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://localhost:2000/quick/Marshal.4.8/activesupport-4.0.13.gemspec.rz)
```

Regards

**Comment by iiezhachenko** [comment]
It returns 404, but gem refuses to search in other sources.
Thanks a lot for your effort. I'll look deeper into gem resolving mechanisms to find needed algorithm.

**Comment by PierreRambaud** [comment]
I pushed a new version on rubygems for you ;) 
Thanks again for your feedback
