### ISSUE TITLE
Undefined method peach (server.rb,update_indexes)

### ISSUE THREAD

**Issue by conathan** [PierreRambaud/gemirro#54]
In lib/gemirro/server.rb, under update_indexes, indexer.updated_gems.peach do |gem| complains that peach is undefined.

I suspect this may have been meant to be from https://github.com/pezra/parallel-each, but I don't see that installed as a gem.

E, [2018-04-19T15:31:16.811914 #13889] ERROR -- : undefined method `peach' for ["/gems/rubygems.org2/public/gems/highline-1.7.10.gem"]:Array
Did you mean?  each (NoMethodError)
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/gemirro-1.0.0/lib/gemirro/server.rb:176:in `update_indexes'
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/gemirro-1.0.0/lib/gemirro/server.rb:155:in `fetch_gem'
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/gemirro-1.0.0/lib/gemirro/server.rb:262:in `spec_for'
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/gemirro-1.0.0/lib/gemirro/server.rb:222:in `block (2 levels) in gem_dependencies'
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/parallel-1.12.1/lib/parallel.rb:484:in `call_with_index'
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/parallel-1.12.1/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/parallel-1.12.1/lib/parallel.rb:495:in `with_instrumentation'
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/parallel-1.12.1/lib/parallel.rb:341:in `block in work_in_threads'
/usr/lib/rvm/gems/ruby-2.4.0@gemirro/gems/parallel-1.12.1/lib/parallel.rb:206:in `block (2 levels) in in_threads'

**Comment by PierreRambaud** [comment]
Thanks a lot for your feedback. I don't use parallel-each anymore. ;)
