### ISSUE TITLE
Issues with gems providing for multiple platforms

### ISSUE THREAD

**Issue by conathan** [PierreRambaud/gemirro#55]
I was running into a issue where suddenly a game would return 404, and looking in the gems folder would show it had the mingw version only.  Repeated attempts would only ignore downloading anything at all.  Restarting gemirro then would give the mingw version instead of the expected ruby version.

nokogiri is one such example.

gem install nokogiri -q --no-rdoc --no-ri -v "1.8.2"

I believe this could be due to  ignore_gem not taking the platform into account,  so it would have a list of  4 gems to go through, but the first one (x86-mingw32) would say ignore_gem(name,version), and it wouldn't download the other 3.

I worked around it by putting a 3rd parameter on ignore_gem/ignore_gem?(name,version,platform) that used  "#{version}-#{platform}" as a key, but not extensively tested.

**Comment by PierreRambaud** [comment]
Hi and thanks for the feedback, I will try to reproduce and apply your fix as soon as possible. Otherwise if you have the time to send me a pull request, don't hesitate, I will be glad to check it! 
Regards
