### ISSUE TITLE
"gemirro update" causes requirement.rb:240:in `satisfied_by?': Need a Gem::Version: nil

### ISSUE THREAD

**Issue by sergiik** [PierreRambaud/gemirro#58]
cd  /tmp/rubygem/

docker run -v /tmp/rubygem/:/tmp rubygem/gemirro init

vim config.rb and add asciidoctor-pdf
...
  define_source 'rubygems', 'http://rubygems.org' do
    gem "asciidoctor-pdf"
  end
..

gem can't be installed with "gemirro update"
docker run -v /tmp/rubygem/:/tmp rubygem/gemirro update
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/requirement.rb:240:in `satisfied_by?': Need a Gem::Version: nil (ArgumentError)
	from /usr/local/bundle/gems/gemirro-0.9.1/lib/gemirro/

But it can be installed sucessfully with "gem install asciidoctor-pdf --pre"

Why the error happens with gemirro update?

**Comment by PierreRambaud** [comment]
Hi and thanks for the feedback.
Do you have a DockerFile or docker-compose to reproduce your problem?
Regards

**Comment by sergiik** [comment]
Hi
https://hub.docker.com/r/rubygem/gemirro/~/dockerfile/

**Comment by sergiik** [comment]
gemirro version in docker is old one. I will retest with newest one

**Comment by PierreRambaud** [comment]
How thanks, dunno they provide a Dockerfile for that :P
I will have a check on tomorrow if you still have the problem with the latest version ;)

**Comment by sergiik** [comment]
With gemirro v1.1.0 there is no issue. Case is closed. Sorry for bothering you

**Comment by PierreRambaud** [comment]
You don't bother me, now I know a Dockerfile exist. Thanks to you ;)
