### ISSUE TITLE
Can't bundle install

### ISSUE THREAD

**Issue by wortmanb** [PierreRambaud/gemirro#67]
I'm 100% certain this is an issue with my current system and am only wondering if anyone has seen this before or has an idea of what might be causing it. It's a CentOS 7 system, and I was able to successfully build gemirro on an AWS instance that's almost identically configured. But what I get on our local server is this:

```
bash-4.2$ rvm use 2.5.8 --default
Using /home/bretw/.rvm/gems/ruby-2.5.8
bash-4.2$ cd git/gemirro/
bash-4.2$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching rake 12.3.1
Installing rake 12.3.1
Errno::EOPNOTSUPP: Operation not supported - copy_file_range
An error occurred while installing rake (12.3.1), and Bundler cannot continue.
Make sure that `gem install rake -v '12.3.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rake
bash-4.2$ gem install rake -v '12.3.1' --source 'https://rubygems.org/'
ERROR:  While executing gem ... (Errno::EOPNOTSUPP)
    Operation not supported - copy_file_range
bash-4.2$ 
```
Is this something anyone else has seen before?

**Comment by PierreRambaud** [comment]
> Errno::EOPNOTSUPP: Operation not supported - copy_file_range

Hi,
seems to be a permission problem. are you sure your user has the right to write in rvm directory; Is it owned by root instead?

**Comment by wortmanb** [comment]
It's actually a known bug in the 3.10.0 kernel from Redhat. I updated to a version with a fix and now we're rocking.
